[pytest]
markers =
    smoke: Дымовые тесты
    regression: Регрессионные тесты
    e2e: End-to-End тесты
    api: API-тесты
    validation: Валидация схем
    flaky: Нестиабильные тесты
    test: Тесты для проверки / обкатке на CI / CD
# addopts = --bro=firefox
